/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject2;

/**
 *
 * @author sarath kumar
 */
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import net.proteanit.sql.DbUtils;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.*;
import java.awt.print.*;
import javax.swing.JFrame;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;


public class form2 extends javax.swing.JFrame {

    /**
     * Creates new form form2
     */
    public form2() {
        initComponents();
        update_table();
        current_date();
    }
    ResultSet rst=null;
        PreparedStatement pst=null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        c_name = new javax.swing.JTextField();
        c_type = new javax.swing.JComboBox<>();
        seats = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        company_table = new javax.swing.JTable();
        update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        print = new javax.swing.JButton();
        date1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("company id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("company name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("company type");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("seats");

        c_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "product", "service", "Bpo" }));

        insert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insert.setText("insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        company_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        company_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        company_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                company_tableMouseClicked(evt);
            }
        });
        company_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                company_tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(company_table);

        update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        print.setText("print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        date1.setText("date");

        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seats, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_type, 0, 96, Short.MAX_VALUE)
                            .addComponent(c_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(update))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(print))))
                .addGap(150, 150, 150)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(date1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(c_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(c_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert)
                            .addComponent(update)
                            .addComponent(print))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(85, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
       try {
                 Connection con = Connect.ConnectDB();
                 String value1=c_type.getSelectedItem().toString();
                 
                PreparedStatement ps = con.prepareStatement("INSERT INTO company(c_name,seats,c_type)"
                        + "values(?,?,?) ");
                
                ps.setString(1, c_name.getText());
                ps.setString(2, seats.getText());
                 ps.setString(3, value1);
                ps.executeUpdate();
                update_table();
               
                
                JOptionPane.showMessageDialog(null, "Data Inserted");
            } catch (SQLException | HeadlessException ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage());
            } 
    }//GEN-LAST:event_insertActionPerformed

    private void company_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_company_tableKeyPressed
        if((evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN))
        {
         try{
            int row =company_table.getSelectedRow();
            String t=(company_table.getModel().getValueAt(row,0).toString());
            String s="select * from company where c_id="+t ;
            Connection con = Connect.ConnectDB();
            pst = con.prepareStatement(s);
            rst=pst.executeQuery();
            if(rst.next())
            {
                String a=rst.getString("c_id");
                c_id.setText(a);
                String b=rst.getString("c_name");
                c_name.setText(b);
                String c=rst.getString("seats");
                seats.setText(c);
                String d=rst.getString("c_type");
                c_type.setSelectedItem(d);
           
                
            }
        }
        catch(Exception ex)
        {
            
        }   
        }
    }//GEN-LAST:event_company_tableKeyPressed

    private void company_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_company_tableMouseClicked
        try{
            int row =company_table.getSelectedRow();
            String t=(company_table.getModel().getValueAt(row,0).toString());
            String s="select * from company where c_id="+t ;
            Connection con = Connect.ConnectDB();
            pst = con.prepareStatement(s);
            rst=pst.executeQuery();
            if(rst.next())
            {
                String a=rst.getString("c_id");
                c_id.setText(a);
                String b=rst.getString("c_name");
                c_name.setText(b);
                String c=rst.getString("seats");
                seats.setText(c);
                String d=rst.getString("c_type");
                c_type.setSelectedItem(d);
           
                
            }
        }
        catch(Exception ex)
        {
            
        }   
    }//GEN-LAST:event_company_tableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        form1 frm=new form1();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int p=JOptionPane.showConfirmDialog(null,"do you really want to delete" ,"Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        if(!c_id.getText().equals(""))
        {
            try {
               Connection con = Connect.ConnectDB();
                PreparedStatement ps = con.prepareStatement("DELETE FROM company WHERE c_id = ?");
                int id = Integer.parseInt(c_id.getText());
                ps.setInt(1, id);
                ps.executeUpdate(); 
               update_table();
                JOptionPane.showMessageDialog(null, "company Deleted");
            } catch (SQLException ex) {
          
                JOptionPane.showMessageDialog(null, "company Not Deleted");
            }
           
        }else{
            JOptionPane.showMessageDialog(null, "company Not Deleted : No Id To Delete");
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
            String UpdateQuery;
            PreparedStatement ps;
            Connection con = Connect.ConnectDB();
        try {
                    UpdateQuery = "UPDATE company SET c_name = ?, seats = ? , c_type =? " 
                            + "WHERE c_id = ?";
                    ps = con.prepareStatement(UpdateQuery);
                    String value1=c_type.getSelectedItem().toString();
                       
                    ps.setString(1,c_name.getText());
                    ps.setString(2,seats.getText());
                    ps.setString(3, value1);
                    ps.setString(4,c_id.getText());     
                    ps.executeUpdate();
                 update_table();
                    JOptionPane.showMessageDialog(null, "company Updated");
                    
                } 
                  catch (SQLException ex) 
                  {
                    JOptionPane.showMessageDialog(null, "cannot be  Updated");
                   } 
    }//GEN-LAST:event_updateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        c_id.setText("");
        c_name.setText("");
        seats.setText("");
        c_type.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header=new MessageFormat("report print");
        MessageFormat footer=new MessageFormat("page {0,number,integer}");
        try
        {
            company_table.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException ex)
        {
            System.err.format("cannot be printed %s%n",ex.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
       Connection con = Connect.ConnectDB();
        try
        {
            String sql="select * from company where c_name=?";
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
                String a=rst.getString("c_id");
                c_id.setText(a);
                String b=rst.getString("c_name");
                c_name.setText(b);
                String c=rst.getString("seats");
                seats.setText(c);
                String d=rst.getString("c_type");
                 c_type.setSelectedItem(d);
                
            }
            
            
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,e);    
        }
        try
        {
            String sql="select * from company where c_id=?";
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
                String a=rst.getString("c_id");
                c_id.setText(a);
                String b=rst.getString("c_name");
                c_name.setText(b);
                String c=rst.getString("seats");
                seats.setText(c);
                String d=rst.getString("c_type");
                 c_type.setSelectedItem(d);
                
            }
            
            
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,e);    
        }
        try
        {
            String sql="select * from company where seats=?";
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
                String a=rst.getString("c_id");
                c_id.setText(a);
                String b=rst.getString("c_name");
                c_name.setText(b);
                String c=rst.getString("seats");
                seats.setText(c);
                String d=rst.getString("c_type");
                 c_type.setSelectedItem(d);
                
            }
            
            
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,e);    
        }
    }//GEN-LAST:event_searchKeyReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed
private void current_date()
{
    Calendar cal=new GregorianCalendar();
    int month=cal.get(Calendar.MONTH);
    int year=cal.get(Calendar.YEAR);
    int day=cal.get(Calendar.DAY_OF_MONTH);
    date1.setText(year+"/"+month+"/"+day);
    
}
        private void update_table()
    {
        Connection con = Connect.ConnectDB();
        
       try
       {
           
           String sql="select * from company";
           pst=con.prepareStatement(sql);
           rst=pst.executeQuery();
           company_table.setModel(DbUtils.resultSetToTableModel(rst));
       }
       catch(Exception e)
       {
        JOptionPane.showMessageDialog(null,e);   
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_name;
    private javax.swing.JComboBox<String> c_type;
    private javax.swing.JTable company_table;
    private javax.swing.JLabel date1;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JTextField search;
    private javax.swing.JTextField seats;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
